# Generated by Django 4.2.4 on 2023-08-09 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MalfunctionOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RepairingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.role')),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.TextField()),
                ('engineNumber', models.TextField()),
                ('transmissionNumber', models.TextField()),
                ('driveAxleNumber', models.TextField()),
                ('steeringAxleNumber', models.TextField()),
                ('deliveryContract_N_data', models.TextField()),
                ('deliveryDate', models.DateField()),
                ('consignee', models.TextField()),
                ('deliveryAdress', models.TextField()),
                ('completeSet', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
                ('driveAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.driveaxlemodel')),
                ('engineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.enginemodel')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.servicecompany')),
                ('steeringAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.steeringaxlemodel')),
                ('transmissionModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.transmissionmodel')),
                ('vehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.role')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('workOrderNumber', models.TextField()),
                ('workOrderDate', models.DateField()),
                ('maintenanceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.maintenancecompany')),
                ('maintenanceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.maintenancetype')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.role'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('malfunctionDescription', models.TextField()),
                ('usedSpareParts', models.TextField()),
                ('repairingDate', models.DateField()),
                ('vehicleDowntime', models.IntegerField()),
                ('malfunctionNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.malfunctionoverview')),
                ('reparingMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.repairingmethod')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vehicle')),
            ],
        ),
    ]
